name: Selenium Regression Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Selenium Tests
        # -pl targets the specific module, -am ensures dependencies are built
        run: mvn clean test -Dheadless=true -pl ui-automation-selenium -am